### ISSUE TITLE
Routing logic

### ISSUE THREAD

**Issue by melbaldove** [Mackignacio/electron-angular-quickstart#5]
Are you sure this uses the state-of-the-art cutting edge routing logic? 
![24058828_10212592843554206_3103594635037517831_n](https://user-images.githubusercontent.com/18225174/52553655-2b7d3300-2e1f-11e9-92b5-41a89a2a11b4.jpg)

**Comment by mackignacio** [comment]
This type of issue are out of scope and not covering any bugs or problem of the project. If you want to know more about Angular routing you refer to this [LINK](https://angular.io/start/routing)
